# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 161d15d32aba98fd5918827f67df827e21adf9330fbd83d7d6405ed06a145a3f3e5b8cbdd54a2aa77de73a5b9d1c8703a1b059e8353bb5e67e1d77c34a4b1eca

test:
  secret_key_base: ade91db464cd6640ac0c49514978ebd731a9bd9592f3569bcb55f4e120baa4ef7944a64fb2eae8485765ea1d108ae1163cd50ee459dbae218abe3c7cd2269b56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
